---
kind: pipeline
type: docker
name: default

steps:
- name: verify_and_build
  image: node
  commands:
  - npm install
  - npm run build
  when:
    exclude:
      branch:
      - master
      - main
      event:
        exclude:
        - pull_request

- name: build_docker_image
  image: plugins/docker
  settings:
    username: 
      from_secret: rergistry_username
    password: 
      from_secret: registry_password
    repo: bohdanpn/supabase-app
    tags: ${DRONE_COMMIT:0:7}
  
